### ISSUE TITLE
企业微信应用推送仅支持pushplus吗

### ISSUE THREAD

**Issue by liwenjie119** [zzsj0928/luci-app-serverchand#1]
因为luci-app-pushbot项目没有开issue，就来这里咨询一下吧，我看README说支持企业微信应用推送，但是编译完发现企业微信只是企业微信机器人，而pushplus里有企业微信应用推送。请问大佬没有支持企业微信应用直接推送吗？因为这个原因直接去除了企业微信应用推送吗？
`因微信推送存在诸多弊端（无法分开聊天工具与功能性消息推送，通知内不显示内容，内容需要点开才能查看等）`

**Comment by zzsj0928** [comment]
+感谢提醒，pushbot 打开issues了。
企业微信应用推送就是由PushPlus提供的，暂时没有计划做这个渠道的直推
